While upgrading to Rails 3.1, I was receiving the error message:
  /Library/Ruby/Gems/1.8/gems/actionpack-3.1.1/lib/action_view/railtie.rb:34:in `send': undefined method `debug_rjs=' for ActionView::Base:Class (NoMethodError)

which was caused by this line in config/environments/development.rb:

  config.action_view.debug_rjs = true

The 'debug_rjs=' function has apparently been deprecated:

  https://github.com/rails/rails/issues/2098

Removing the call fixed the problem.